### ISSUE TITLE
Get_parameters is not returning required data

### ISSUE THREAD

**Issue by Allouche-M** [NueveCuatro/AI-for-coding-green-videos#1]
Bonjour, j'ai lancé le get_parameters et voici le retour que j'ai eu:
`Paramètres de codage vidéo :
{
    "programs": [],
    "streams": [
        {
            "codec_name": "h264",
            "width": 1920,
            "height": 1080
        }
    ]
}`
Alors que ffprobe peut vous donner beaucoup plus de données que ça (**exemple de json en pièce jointe**)
[video_info.json](https://github.com/NueveCuatro/AI-for-coding-green-videos/files/13167621/video_info.json)

**Comment by Mzoughh** [comment]
Bonjour l'erreur a été corrigée.
